<?php

namespace App\Http\Requests\Parent\CreditCard;

use App\Http\Requests\CreditCardRequest;
use Illuminate\Contracts\Validation\Validator;

class StoreCardRequest extends CreditCardRequest
{
    public function __construct(array $query = [], array $request = [], array $attributes = [], array $cookies = [], array $files = [], array $server = [], $content = null)
    {
        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content);
    }

    public function rules()
    {
        $rules =  parent::rules(); // TODO: Change the autogenerated stub
        $rules['cardAlias'] = 'required';
        return $rules;
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
