<?php

namespace App\Models;


use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Passport\HasApiTokens;

class BabySitter extends Authenticatable
{
    use HasApiTokens, Notifiable, SoftDeletes;

    protected $hidden = [];
    protected $guarded = [];
    protected $appends = ['last_name', 'has_calendar_for_future'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->uuid = Str::uuid();
        });
    }


    public function experience_count(){
        return $this->appointments()->count();
    }

    public function getLastNameAttribute()
    {
        try {
            return mb_strtoupper($this->surname[0]) . '.';
        } catch (\Exception $exception) {
            return '';
        }
    }

    public function modelName()
    {
        return 'App\BabySitter';
    }

    public function sms_codes()
    {
        return $this->hasMany(BabySitterSmsCode::class);
    }

    public function gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function available_towns()
    {
        return $this->belongsToMany(Town::class, 'baby_sitter_regions')->where('is_active', true);
    }

    public function shareable_talents()
    {
        return $this->belongsToMany(ShareableTalent::class, 'baby_sitter_shared_talents', 'baby_sitter_id', 'shareable_talent_id');
    }

    public function baby_sitter_available_dates()
    {
        return $this->hasMany(BabySitterAvailableDate::class);
    }



    public function accepted_locations()
    {
        return $this->belongsToMany(AppointmentLocation::class, 'baby_sitter_appointment_locations', 'baby_sitter_id', 'location_id');
    }


    public function appointments()
    {
        return $this->hasMany(Appointment::class);
    }



    public function points()
    {
        return $this->hasMany(BabySitterPoint::class);
    }

    public function child_gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function parent_gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function child_years()
    {
        return $this->belongsToMany(ChildYear::class, 'baby_sitter_child_years', 'baby_sitter_id', 'child_year_id');
    }


    /**
     * Scopes
     * @param $query
     * @param string $phone
     * @return mixed
     */
    public function scopePhone($query, string $phone)
    {
        return $query->where('phone', $phone);
    }

    public function scopeAcceptedLocation($query, $acceptedLocationId)
    {
        return $query->whereHas('accepted_locations', function ($q) use ($acceptedLocationId) {
            $q->where('location_id', $acceptedLocationId);
        });
    }

    public function scopeChildGenderStatus($query, $childGender)
    {
        if ($childGender != null) {
            $query->whereRaw('( child_gender_id = ' . $childGender . '  OR child_gender_id = 3 )');
        } else {
            $query->whereRaw('( child_gender_id = 3 )');
        }
        return $query;
    }

    public function scopeAcceptsDisabledChild($query, $disable)
    {
        if ($disable)
            $query->where('disabled_status', 1);
        return $query;
    }

    public function scopeGender($query, $genderId = null)
    {
        if ($genderId && $genderId != 3) {//3 Farketmez
            $query->where('gender_id', $genderId);
        }
        return $query;
    }

    public function scopeChildrenCount($query, $count)
    {
        return $query->where('child_count', '>=', $count);
    }



    public function scopeAvailableTown($query, $townId)
    {
        return $query->whereHas('available_towns', function ($q) use ($townId) {
            $q->where('town_id', $townId);
        });
    }

    public function scopeDateTime($query, $date, array $times)
    {
        return $query->whereHas('baby_sitter_available_dates', function ($q) use ($date, $times) {//O gün yer var mı ?
            $q->where('date', Carbon::make($date));

            foreach ($times as $time) {
                $q->whereHas('times', function ($q1) use ($time) {//O günün saatlerinde yer var mı varsa meşgul mü değil mi ?
                    $q1->where('start', $time)->where('time_status_id', 1);
                });
            }
        });
    }

    public function scopeBabySitterId($query, $id)
    {
        return $query->where('id', $id);
    }

    public function scopePricePerHour($query)
    {
        return $query->where('price_per_hour', '>', 0);
    }

    public function scopeWcStatus($query, $status)
    {
        if ($status) {
            return $query->where('wc_status', true);
        }
        return $query;
        // return $query->where('wc_status', false)->orWhere('wc_status', null);
    }

    public function scopeAnimalStatus($query, $status)
    {
        if ($status) {
            return $query->where('animal_status', true);
        }
        return $query;

        //return $query->where('wc_status', false)->orWhere('wc_status', null);

    }

    public function scopeShareableTalents($query, $talents)
    {
        if (is_array($talents) && count($talents)) {
            return $query->whereHas('shareable_talents', function ($q) use ($talents) {
                $q->whereIn('shareable_talent_id', $talents);
            });
        }
        return $query;
    }

    public function scopeChildYears($query, $childYears)
    {
        if (is_array($childYears) && count($childYears)) {
            return $query->whereHas('child_years', function ($q) use ($childYears) {
                $q->whereIn('child_year_id', $childYears);
            });
        }
        return $query;
    }

    public function getHasCalendarForFutureAttribute()
    {
        return $this
                ->baby_sitter_available_dates()
                ->whereBetween('date', [now(), now()->addDays(15)])
                ->count() > 0;
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

}
