<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class BabySitterDeposit extends Model
{
    protected $guarded = [];
    protected $casts = ['raw_result' => 'object'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updated(function ($model) {
            if (isset($model->raw_result->status) && $model->raw_result->status == "success"){
                $babySitter=$model->baby_sitter;
                $babySitter->deposit = 30;
                $babySitter->save();
            }
        });
    }

    public function baby_sitter()
    {
        return $this->belongsTo(BabySitter::class);
    }
}
