<?php

namespace App\Models;


use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Passport\HasApiTokens;

class Parents extends Authenticatable
{
    use  HasApiTokens, Notifiable, SoftDeletes;

    protected $table = 'parents';
    protected $appends = ['has_registered_card', 'last_name'];
    protected $hidden = ['card_parents'];
    protected $guarded = [];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->uuid = Str::uuid();
        });
    }

    public function getLastNameAttribute()
    {
        try {
            return mb_strtoupper($this->surname[0]) . '.';
        } catch (\Exception $exception) {
            return '';
        }
    }

    public function isReadyToCreateAppointment()
    {
        return !(is_null($this->name)
            || is_null($this->surname)
            || is_null($this->email)
            || is_null($this->tc)
            || is_null($this->phone)
            || is_null($this->birthday)
            || is_null($this->photo)
            || is_null($this->gender_id));
    }

    public function modelName()
    {
        return '\Parents';
    }

    public function sms_codes()
    {
        return $this->hasMany(ParentSmsCode::class, 'parent_id');
    }

    public function card_parents()
    {
        return $this->hasMany(CardParent::class, 'parent_id');
    }

    public function gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function appointments()
    {
        return $this->hasMany(Appointment::class, 'parent_id')->with("baby_sitter:id,name,surname,photo,point");
    }

    public function scopePhone($query, $phone)
    {
        return $query->where('phone', $phone);
    }

    public function getHasRegisteredCardAttribute()
    {
        return count($this->card_parents) > 0;
    }

    public function favorite_baby_sitters()
    {
        return $this->belongsToMany(BabySitter::class, 'favorites', 'parent_id', 'baby_sitter_id');
    }
}
