version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:1.7.4-alpine
    restart: always
    depends_on:
      - laravel
    command: --docker
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:monitor.oymt.xyz
      - traefik.port=8080
    networks:
      - proxy
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
  laravel:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./laravel
      dockerfile: ./Dockerfile
    image: laravel
    restart: always
    container_name: laravel
    tty: true
    labels:
      - traefik.enable=false
    depends_on:
      - postgres
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/php.ini
      - ./laravel/:/var/www
    networks:
      - local-bridge
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:api.oymt.xyz
      - traefik.port=80
    depends_on:
      - postgres
    volumes:
      - ./laravel/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - local-bridge
      - internal


  postgres:
    container_name: postgres_container
    image: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_DB: yuffi
      POSTGRES_USER: ${POSTGRES_USER:-omermutlu}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Omer@2015}
      PGDATA: /data/postgres
    volumes:
      - ./postgres/:/data/postgres
    labels:
      - traefik.enable=false
    ports:
      - "5432:5432"
    networks:
      - local-bridge
    restart: unless-stopped

  echo:
    container_name: echo_server
    build:
      context: ./echo
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:echo.oymt.xyz
      - traefik.port=80
    networks:
      - local-bridge
      - internal


  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - local-bridge
      - internal

networks:
  local-bridge:
    driver: bridge
  proxy:
    external: true
  internal:
