<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class CalendarGetResource extends JsonResource
{
    public function toJson($options = 1)
    {
        return parent::toJson($options); // TODO: Change the autogenerated stub
    }

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        $data = [];
        $data[$this->date] = $this->prapareString($this);
        return $data;
    }

    public static function prapareString($date)
    {
        $existTimes = [];
        $nonExistsTimes = [];
        $nonExistsTimesTemp = [];
        for ($i = 10; $i < 22; $i++) {
            $string['starts'] = $i . ':00:00';
            $string['end'] = $i + 1 . ':00:00';
            $string['name'] = $i . ':00:00' . ' ' . ($i + 1) . ':00:00';
            $string['status_id'] = 999;//Eklenmemiş
            $nonExistsTimes[$i . ':00:00'] = $string;
        }

        foreach ($date->times as $time) {
            if (isset($nonExistsTimes[$time->start])) {
                unset($nonExistsTimes[$time->start]);
            }
            $string['starts'] = $time->start;
            $string['end'] = $time->finish;
            $string['name'] = $time->start . ' ' . $time->finish; //. ' ve ' . $time->time_status->name;
            $string['status_id'] = $time->time_status_id;
            $existTimes[] = $string;
        }
        foreach ($nonExistsTimes as $key => $value) {
            $nonExistsTimesTemp[] = $value;
            unset($nonExistsTimes[$key]);
        }

        return collect(array_merge($nonExistsTimesTemp, $existTimes))->sortBy('starts')->values();


    }

    public static function fillTimesToNonExistDate()
    {
        $data = [];
        for ($i = 10; $i < 22; $i++) {
            $string['starts'] = $i . ':00:00';
            $string['end'] = $i + 1 . ':00:00';
            $string['name'] = $i . ':00:00' . ' ' . ($i + 1) . ':00:00';
            $string['status_id'] = 999;//Eklenmemiş
            $data[] = $string;
        }
        return $data;
    }
}
